<?php

namespace app\modules\admin\models;

use app\models\BlogComent;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "blog".
 *
 * @property int $id
 * @property string $name
 * @property string $img
 * @property string $content
 * @property string $created_at
 * @property string $keywords
 * @property string $description
 * @property string $small_content
 */
class Blog extends \yii\db\ActiveRecord
{
    public $file;
    public function  behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ],
                // если вместо метки времени UNIX используется datetime:
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    public function getBlogComent(){
        return $this->hasMany(BlogComent::className(),['id'=>'blog_id']);
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'content','small_content'], 'required'],
            [['content', 'keywords', 'description', 'small_content','username'], 'string'],
            [['created_at'], 'safe'],
            [['name', 'image'], 'string', 'max' => 255],
            [['file'], 'image']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя блога',
            'content' => 'Контент',
            'date' => 'Время создания',
            'keywords' => 'Ключевые слова',
            'description' => 'Мета-описание',
            'small_content' => 'Небольшой текст (который на preview)',
            'image' => 'Картинка',
        ];
    }
    public function beforeSave($insert)
    {
        if($file = UploadedFile::getInstance($this,'file')){
            $dir = 'upload/blog/';
            $this->image = $file->baseName . '_' . Yii::$app->getSecurity()->generateRandomString(7) . '.' . $file->extension;
            $file->saveAs($dir.$this->image);
            return $file;
            }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
