<?php

namespace app\modules\admin\models;

use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\UploadedFile;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property string|null $keywords
 * @property string|null $description
 * @property string $img
 */
class Category extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }
    public function getCategory(){
        return $this->hasOne(Category::className(),['id'=>'parent_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent_id'], 'integer'],
            [['name'], 'required'],
            [['name', 'keywords', 'description', 'img'], 'string', 'max' => 255],
            [['file'],'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Номер категории',
            'parent_id' => 'Родитель категории',
            'name' => 'Имя',
            'keywords' => 'Ключевые слова',
            'description' => 'Мета-Описание',
            'img' => 'Картинка',
        ];
    }
    public function beforeSave($insert)
    {
        if($file = UploadedFile::getInstance($this,'file')){
            $dir = 'upload/category/';
            $this->img = $file->baseName.'.'.$file->extension;
            $file->saveAs($dir.$this->img);
            return $file;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub

    }

    public function getImgP(){
        return Html::img('/upload/category/'.$this->img);
    }
    public function getImage(){
        if($this->img){
            $path =  str_replace('admin.','',Url::home(true)).'upload/category/'.$this->img;
        }else{
            $path = str_replace('admin.','',Url::home(true)).'upload/category/no-image.png';
        }

        return $path;
    }
}
